model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss
    image_key: to
    ddconfig:
      double_z: false
      z_channels: 1
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 1000
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: true
    train:
      target: ldm.datasets.custom_datasets.DepthDatasetTrain
      params:
        size: 256
    validation:
      target: ldm.datasets.custom_datasets.DepthDatasetVal
      params:
        size: 256

lightning:
  trainer:
    max_epochs: 50
    num_sanity_val_steps: 0    

