model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: to
    cond_stage_key: from
    translation_label: True
    image_size: 64
    channels: 1
    # sensor_config: depth_semantic # change sensor config here to train different models (not necessary yet)
    concat_mode: False
    cond_stage_trainable: True
    second_pretrained: False
    second_code: False
    conditioning_key: conditional_translation
    

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: libs.uvit_decoder_view.UViT
      params:
        img_size: 64
        in_chans: 3
        patch_size: 4
        embed_dim: 768
        depth: 28
        num_heads: 12
        mlp_ratio: 4
        qkv_bias: False
        mlp_time_embed: False
        use_checkpoint: False
        conv: False
        translation_distance_dim: 4

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # ckpt_path: /home/nianyli/Desktop/code/thesis/DiffViewTrans/saved_experiments/3d_depth_instance_v2/vqgan_depth_epoch_69.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 4
          out_ch: 4
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: false
        z_channels: 3
        resolution: 256
        in_channels: 4
        out_ch: 4
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 5
    wrap: False
    train:
      target: ldm.datasets.custom_datasets.RGBDepthDatasetTrain  #  PUT YOUR DATASET 
      params:
        size: 256
    validation:
      target: ldm.datasets.custom_datasets.RGBDepthDatasetVal  #  PUT YOUR DATASET 
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 4
        increase_log_steps: False 
  trainer:
    num_sanity_val_steps: 0
    benchmark: True
    check_val_every_n_epoch: 1
    
